package com.delivery.entity;

import java.io.Serializable;
import lombok.Data;

import javax.persistence.*;

/**
 * generated by Generate POJOs.groovy 
 * @Date 2020-10-20 16:35
 *
 * @author Yvan
 */

@Data
@Entity
@Table ( name ="city" )
public class City implements Serializable {

	private static final long serialVersionUID = 4180067055637627917L;

 	@Column(name = "id" )
	@Id
	@GeneratedValue
	private String id;

	/**
	 * 市名
	 */
 	@Column(name = "city_name" )
	private String cityName;

	/**
	 * 省id
	 */
 	@Column(name = "province_id" )
	private String provinceId;

}
