package com.delivery.entity;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy
 *
 * @author Yvan
 * @Date 2020-10-21 19:46
 */

@Data
@Entity
@Table(name = "customer_address")
public class CustomerAddress implements Serializable {

    private static final long serialVersionUID = 5021435919735379164L;

    @Column(name = "id")
    @Id
    @GeneratedValue
    private Integer id;

    /**
     * 省id
     */
    @Column(name = "province_id")
    private String provinceId;

    /**
     * 市id
     */
    @Column(name = "city_id")
    private String cityId;

    /**
     * 区id
     */
    @Column(name = "area_id")
    private String areaId;

    /**
     * 用户详细地址
     */
    @Column(name = "address_detail")
    private String addressDetail;

    /**
     * 用户id
     */
    @Column(name = "user_id")
    private Integer userId;

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CustomerAddress)) {
            return false;
        }

        CustomerAddress that = (CustomerAddress) o;

        if (getProvinceId() != null ? !getProvinceId().equals(that.getProvinceId()) : that.getProvinceId() != null) {
            return false;
        }
        if (getCityId() != null ? !getCityId().equals(that.getCityId()) : that.getCityId() != null) {
            return false;
        }
        if (getAreaId() != null ? !getAreaId().equals(that.getAreaId()) : that.getAreaId() != null) {
            return false;
        }
        if (getAddressDetail() != null ? !getAddressDetail().equals(that.getAddressDetail()) : that.getAddressDetail() != null) {
            return false;
        }
        return getUserId() != null ? getUserId().equals(that.getUserId()) : that.getUserId() == null;
    }

    @Override
    public int hashCode() {
        int result = getProvinceId() != null ? getProvinceId().hashCode() : 0;
        result = 31 * result + (getCityId() != null ? getCityId().hashCode() : 0);
        result = 31 * result + (getAreaId() != null ? getAreaId().hashCode() : 0);
        result = 31 * result + (getAddressDetail() != null ? getAddressDetail().hashCode() : 0);
        result = 31 * result + (getUserId() != null ? getUserId().hashCode() : 0);
        return result;
    }
}
