package com.delivery.entity;

import java.io.Serializable;
import lombok.Data;

import javax.persistence.*;

/**
 * generated by Generate POJOs.groovy 
 * @Date 2020-10-20 16:35
 *
 * @author Yvan
 */

@Data
@Entity
@Table ( name ="provinces" )
public class Provinces implements Serializable {

	private static final long serialVersionUID = 8250486350106880409L;

 	@Column(name = "id" )
	@Id
	@GeneratedValue
	private String id;

 	@Column(name = "province_name" )
	private String provinceName;

}
