package com.delivery.entity;

import java.io.Serializable;
import lombok.Data;

import javax.persistence.*;

/**
 * generated by Generate POJOs.groovy 
 * @Date 2020-10-18 16:46
 *
 * @author Yvan
 */

@Data
@Entity
@Table ( name ="sender" )
public class Sender implements Serializable {

	private static final long serialVersionUID = 3624250254514828007L;

 	@Column(name = "id" )
	@Id
	@GeneratedValue
	private Integer id;

	/**
	 * 编号
	 */
 	@Column(name = "sender_num" )
	private String senderNum;

	/**
	 * 姓名
	 */
 	@Column(name = "sender_name" )
	private String senderName;

	/**
	 * 手机号码
	 */
 	@Column(name = "sender_phone" )
	private String senderPhone;

	/**
	 * 作废标记

	 */
 	@Column(name = "sender_cancell" )
	private Integer senderCancell;

	/**
	 * 所属单位

	 */
 	@Column(name = "sender_unit" )
	private String senderUnit;

	/**
	 * 收派标准
	 */
 	@Column(name = "sender_standard" )
	private String senderStandard;

}
