package com.delivery.entity;

import java.io.Serializable;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * @Date 2020-10-16 18:06
 *
 * @author Yvan
 */

@Data
@Entity
@Table ( name ="user" )
public class User implements Serializable {

	private static final long serialVersionUID = 627819087877502390L;

 	@Column(name = "id" )
	@Id
	@GeneratedValue
	private Integer id;

	/**
	 * 用户编号
	 */
 	@Column(name = "user_number" )
	private String userNumber;

	/**
	 * 用户名
	 */
 	@Column(name = "user_name" )
	private String userName;

	/**
	 * 密码
	 */
 	@Column(name = "user_password" )
	private String userPassword;

	/**
	 * 工资
	 */
 	@Column(name = "user_salary" )
	private Double userSalary;

	/**
	 * 生日

	 */
 	@Column(name = "user_date" )
	private Date userDate;

	/**
	 * 性别
	 */
 	@Column(name = "user_gender" )
	private String userGender;

	/**
	 * 单位
	 */
 	@Column(name = "user_company" )
	private String userCompany;

	/**
	 * 手机
	 */
 	@Column(name = "user_phone" )
	private String userPhone;

	/**
	 * 备注
	 */
 	@Column(name = "user_remark" )
	private String userRemark;

	/**
	 * 邮箱
	 */
 	@Column(name = "email" )
	private String email;

}
